language: python
python:
    - "3.6"

before_install:
    - sudo apt-get update
    - sudo apt-get -y install doxygen graphviz plantuml
    - sudo pip install pipenv

install:
    - pipenv install --dev

script:
    - cd doxygen && doxygen Doxyfile && cd ..
    - pipenv run travis-sphinx build --source=source --nowarn

after_success:
    - pipenv run travis-sphinx deploy

